### ISSUE TITLE
"UTF-8" vs "utf-8" in the encoded prolog?

### ISSUE THREAD

**Issue by thbar** [qcam/saxy#101]
Thanks for Saxy! A great library :smile:

While implementing a round-trip operation (parsing, modifying, re-encoding) of small XML documents, and comparing the before/after as a way to test the operation, I noticed that it is possible to generate a document with the encoding specified via this code:

https://github.com/qcam/saxy/blob/9f9b372b0fb93ee8fbbad527298e8a7a2fef6660/lib/saxy/encoder.ex#L29-L31

The documents I'm usually dealing with use an uppercase encoding here (`UTF-8`), and it is often quoted on the net that the uppercase variant is preferred (https://blog.codingoutloud.com/2009/04/08/is-utf-8-case-sensitive-in-xml-declaration/).

I am a bit concerned that some legacy / low-quality parsers could choke on the lower-case version.

So I wonder: would you be OK to also support the uppercase version?

Also, it could be nice to have the option to add a newline after the prolog, as commonly seen in indented document.

If you are interested, I'll be happy to contribute this via a PR. Thanks!

**Comment by qcam** [comment]
Yes, that sounds like a great idea to me. A PR will be appreciated. Thanks.

**Comment by thbar** [comment]
Will do, thanks!

**Comment by thbar** [comment]
@qcam PR is ready in #102!

**Comment by qcam** [comment]
Fixed via https://github.com/qcam/saxy/pull/102
