### ISSUE TITLE
Can we safely raise an error from a handler?

### ISSUE THREAD

**Issue by thbar** [qcam/saxy#105]
I am "overriding" the Saxy.SimpleForm.Handler (using it as a basis, and overriding one function), and I was wondering if there is a risk of memory leak or similar trouble if an exception is raised from `handle_event`.

It is safe to do?

(for some context, I've read https://github.com/qcam/saxy/issues/80).

Thanks!

**Comment by qcam** [comment]
Not sure if I understand your question completely but Saxy doesn't do any special error handling. Any exception raised in the handler will just simply stop the parser and leave to the users to handle.

**Comment by thbar** [comment]
Excellent. Some libraries keep state around so I preferred to ask. Thanks for the confirmation!
