### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by roelandvanbatenburg** [qcam/saxy#112]
We are using Saxy to parse XML files provided by our users. We are only interested in some elements, so Saxy perfectly suits our needs. However, sometimes our users introduce namespaces in the XML and we receive something like

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<fruitset xmlns:ns2="https://www.w3schools.com/fruit">
  <fruit>
    <ns2:name>Banana</ns2:name>
    <colour>Yellow</colour>
  </fruit>
</fruitset>
```

Where we are only interested in the `name` value. We can modify the `handle_event` of `:start_element` to ignore the namespace, but http://www.saxproject.org/namespaces.html mentions a variable `localName`. Are there any plans to add such a parameter to the `:start_element` event?

**Comment by qcam** [comment]
@roelandvanbatenburg Hi, I don't think Saxy will be supporting namespaces on its own but it should be possible for the users to build namespaces on top of it.

Not sure if I understand completely but I guess `localName` could be extracted with something like:

```ex
[_, local_name] = String.split(tag_name, parts: 2)
```

?

**Comment by roelandvanbatenburg** [comment]
@qcam Yes, that certainly works (if you do `String.split(tag_name, ":", parts: 2)`) and we are using that, but to fully support the namespace you also need to parse the `xmlns` attributes. We don't need that, but I thought it might be interesting for Saxy to support this. If not, feel free to close this issue :)

**Comment by qcam** [comment]
Probably Saxy wouldn't support namespaces natively but if somebody from the future puts together a library supporting that please feel free to paste a link here :).
