### ISSUE TITLE
Special characters are not escaped during xml encoding

### ISSUE THREAD

**Issue by ashabhasa** [qcam/saxy#124]
Hello @qcam, thanks for the effort you're putting on this project, it's been really helpful for us.
I'm currently having an issue creating xml documents. 
My expectation was that when I create an xml the special characters in the content will be escaped apparently this is not happening here is an example:

```elixir
> Saxy.XML.element("event", [], "Event1 & Event2") |> Saxy.encode!()
> "<event>Event1 & Event2</event>"
```

Thank you!

**Comment by lucacorti** [comment]
@ashabhasa I think this can be closed, the solution is to use `Saxy.XML.characters` on the value passed to Saxy.XML.element` to ensure data is escaped.
