### ISSUE TITLE
Support scan

### ISSUE THREAD

**Issue by varnerac** [qcam/saxy#21]
Is it possible to have Saxy implement a `scan` call, similar to Erlsom, where we return the remainder of the binary that didn't parse?

https://github.com/willemdj/erlsom/blob/master/src/erlsom.erl#L219-L224

**Comment by qcam** [comment]
@varnerac technically it is possible. Since all `misc` characters (whitespace, comments for example) after the root element are part of the [grammar rule](https://www.w3.org/TR/xml/#sec-well-formed) and Saxy knows how to parse them, so I assume the remainder you meant are characters not part of rule.

Could you give an example in which the remainder binary would be interesting?

**Comment by qcam** [comment]
`scan` sounds useful in this case, let's implement it.

In the mean time, if these XML partials are parts of a well-formed document and you could somehow turn these XML partials into a stream, you could consider using `Saxy.parse_stream/3` :).

**Comment by varnerac** [comment]
I've been looking at how to implement this. My initial thought is to add a non negative integer to for the position of the last emitted value (`last_emit_pos`) in the parsing code.

This call (https://github.com/qcam/saxy/blob/master/lib/saxy/parser.ex#L7) would go from:

```elixir
case parse_prolog(buffer, cont, buffer, 0, state) do
```

to

```elixir
case parse_prolog(buffer, cont, buffer, 0, 0, state) do
```

This call https://github.com/qcam/saxy/blob/master/lib/saxy/parser/element.ex#L64

would become

```elixir
parse_element_content(rest, cont, original, pos + 1, pos, state)
```

to keep track that an element was successfully emitted there.

I'd change `syntax_error` to `end_of_file_or_syntax_error` (better name?)

the `end_of_file_or_syntax_error` function would take `last_emit_pos` and `orig` as additional arguments

if the next token is `<<>>` (`:eof`) then we return the following for a `scan` call:

`{:ok, user_state, rest}` where `rest` is the binary, from `last_emit_pos` to the end

`parse` calls would wrap `scan`, and behave exactly the way they do now. Thoughts?

**Comment by qcam** [comment]
@varnerac Thanks for working on this.

I'm thinking perhaps we can avoid introducing new `last_emit_pos` by using the `original` binary, which will be committed every time we finish emitting an element https://github.com/qcam/saxy/blob/master/lib/saxy/parser/element.ex#L84.

I think returning the `user_state` is not enough, we need to also return the `stack` (which holds all the parents of the current element ), so the parser knows when to terminate parsing https://github.com/qcam/saxy/blob/master/lib/saxy/parser/element.ex#L78.

**Comment by qcam** [comment]
@varnerac I've been improving the streaming part of the parser last 2 days in order to make `scan` implementation easier. So if you specify the second argument of `Saxy.Prolog.parse_prolog/5` as `true`, it will return `{:halted, context_fun}` with `context_fun` being a function holding all the information that needed to continue parsing.

You might want to check out how streaming parser implement that at:

https://github.com/qcam/saxy/blob/d25cb67ff72c3e55dc2ea81fa78b832bffc4ffac/lib/saxy.ex#L252

**Comment by varnerac** [comment]
I haven't forgotten this. I've just been tied up. Hope to tackle it soon. Thanks for the changes that make implementing this feature easier.

**Comment by liberza** [comment]
I implemented this using the `context_fun` and it appears to work:

```
  def parse_partial(data, context_fun)
      when is_binary(data) do
    context_fun.(data, true)
  end

  def parse_partial(data, handler, initial_user_state, options \\ [])
      when is_binary(data) and is_atom(handler) do
    expand_entity = Keyword.get(options, :expand_entity, :keep)

    state = %State{
      prolog: nil,
      handler: handler,
      user_state: initial_user_state,
      expand_entity: expand_entity
    }

    Parser.Prolog.parse(<<>>, true, <<>>, 0, state)
  end
```

Calling `context_fun.(<<>>, false)` spits out a fully-formed %Saxy.State{} when the fully-formed document has been fed in a little bit at a time. 

My main question is: is there a way to get the current user-state out of `context_fun` while parsing is still incomplete?

**Comment by liberza** [comment]
My first stab at it is in this commit: https://github.com/liberza/saxy/commit/ef30b2da5068451644a4c71a3cf3c2feb3ed8031

Usage:
```elixir
{:ok, fun} = Saxy.parse_partial_init(MyParser, initial_state)
{:ok, fun} = Saxy.parse_partial(some_xml, fun)
{:ok, fun} = Saxy.parse_partial(final_xml, fun)
{:ok, state} = Saxy.parse_partial_done(fun)
```

**Comment by liberza** [comment]
Looking into this some more, it seems like it may just be easier to get state updates using `handle_event/3` to call out to a GenServer each time, using a pid passed in via the initial state. Then it wouldn't need to be implemented in Saxy itself, just the `parse_partial*` stuff. I'll make a pull request for this if it looks OK.

**Comment by qcam** [comment]
Closing in favor of #42.
