### ISSUE TITLE
Patch release

### ISSUE THREAD

**Issue by rozap** [qcam/saxy#26]
Hi! This is a great library, and I converted my library to use it instead of xmerl, and it's much better now. Just wondering if you could do a patch release to hex, as I depend on e8f93474 (removal of the stream match in `parse_stream/3`). I would use github master, but hex deps can't depend on github deps (my lib is exkml).

Thanks!

**Comment by qcam** [comment]
@rozap Hi, thanks for using the library ❤️. [v0.8.0](https://hex.pm/packages/saxy/0.8.0) has been released on hex.
