### ISSUE TITLE
:bad_return error returned when parsing a valid XML file

### ISSUE THREAD

**Issue by vruizext** [qcam/saxy#32]
I get an error trying to parse a small sample of discogs data dump. I could parse the same file without any issues in Ruby and Python.

The error is raised right after the prolog, the first element is not processed. 
```
iex(4)> DiscogsParserEx.run('data/masters_sample.xml')
"Start parsing document"
{:error,
 %Saxy.ParseError{
   binary: nil,
   position: nil,
   reason: {:bad_return, {:start_document, [start_document: []]}}
 }}
```

I'm trying to figure out what's going on, and the meaning of `bad_return`, which I believe is returned here: https://github.com/qcam/saxy/blob/d043f560cc3cd48c5995d319d3581ea2830754ed/lib/saxy/parser/prolog.ex#L310

Here a link to the files I'm trying to parse 
https://github.com/alexquintino/discogs-parser/tree/master/data

These files don't have a prolog. But I've tried to add the prolog and still get the same error 

```
iex(5)> DiscogsParserEx.run('data/masters_sample.xml')
"Start parsing document"
{:error,
 %Saxy.ParseError{
   binary: nil,
   position: nil,
   reason: {:bad_return, {:start_document, [start_document: [version: "1.0"]]}}
 }}
```

Do you have any clue of why the parser raises this error? Any help would be appreciated, thanks!

**Comment by vruizext** [comment]
I found the problem, the error is in the code you provide for `MyEventHandler` in in  README.md, https://github.com/qcam/saxy/blame/master/README.md#L40

The output in the methods, it's not matching the pattern expected by the parser 

The method should return something like this:
`{:ok, [{:start_document, prolog} | state]}`

**Comment by vruizext** [comment]
Disclaimer: I'm a total Elixir noob, it took me a while to realize that the error was all about the pattern matching. A more detailed error output would probably help.

**Comment by qcam** [comment]
@vruizext Thanks for the report ❤️. Great to hear that you fixed the error. The example in README is indeed a documentation bug, I will fix that.

`Saxy.parse_string` guarantees the error returned to be an Elixir exception. So you could use `Exception.message/1` to see the message.

```ex
{:error, exception} = Saxy.parse_string(my_string, ...)
IO.inspect Exception.message(exception)
```

**Comment by qcam** [comment]
Fixed via https://github.com/qcam/saxy/commit/5ac59d2fe61a8cf2ca881246b3a6dabb0b9b8c82
