### ISSUE TITLE
What about really big XML?

### ISSUE THREAD

**Issue by yurgon** [qcam/saxy#36]
FIle size about 30gb
What about speed?
File load in memory ?

Thx

**Comment by qcam** [comment]
@yurgon For large size XML documents, instead of loading them in memory, you can stream the file and use [Saxy.parse_stream/4](https://hexdocs.pm/saxy/Saxy.html#parse_stream/4). It supports Elixir stream and should be memory efficient.

```ex
stream = File.stream!("/path/to/your/file")
{:ok, return_state} = Saxy.parse_stream(stream, YourHandler, init_state)
```

XML parsing speed really depends on the complexity of the document itself. I have never tried any 30GB document but for a fairly simple 716.9MB document on my computer, parsing finished in around 34 seconds. 

Perhaps you can try out a 30GB and let me know? 🙂

**Comment by yurgon** [comment]
Streem not work for me
I dont know why

**Comment by yurgon** [comment]
I do as u said

file_stream = File.stream!("./uploads/AS_STEAD_20181125_0a297695-a6de-40a8-b526-39dbbd2bdb80.XML")
Saxy.parse_stream(file_stream, SaxParser, [type: "Stead"])

SaxParser from example

**Comment by yurgon** [comment]
Maybe some version of modules not valid for me

**Comment by yurgon** [comment]
I dont see any error, I run code in console and nothing happen.

**Comment by yurgon** [comment]
file_stream = File.read!("./uploads/AS_STEAD_20181125_0a297695-a6de-40a8-b526-39dbbd2bdb80.XML")
Saxy.parse_string(file_stream, SaxParser, [type: "Stead"])

Works okay

**Comment by qcam** [comment]
Great to hear that it works. The third parameter is actually the initial state, so you can manipulate the result by returning the desired state in each `handle_event` callback in your `SaxParser`. You can see more how to do that at https://hexdocs.pm/saxy/Saxy.Handler.html#content. :)

**Comment by qcam** [comment]
To ensure it works, can you try printing out the SAX events, by using this small script:

```ex
defmodule MyHandler do
  def handle_event(event_name, _data, state) do
    IO.inspect(event_event)
    {:ok, state}
  end
end

stream = File.stream!("/path/to/your/file")
Saxy.parse_stream(stream, MyHandler, [])
```

and let me know what does it return?

**Comment by qcam** [comment]
That seems strange. Could you upload your XML document somewhere so I can download and run a test on my end?

**Comment by yurgon** [comment]
sure https://drive.google.com/file/d/1mQtKckde-s90-IIwfAHvKltLy2LF3_Qd/view?usp=sharing

**Comment by yurgon** [comment]
First remove "\uFEFF" at the beginning of the file

**Comment by qcam** [comment]
I think the problem is that you need stream by bytes (instead of line-by-line), since your XML file is on one line.

```ex
stream = File.stream!("/path/to/file", [] = _options, 2048 = _bytes)
Saxy.parse_stream(stream, Handler, [])
```

**Comment by yurgon** [comment]
Thank u
U a right!

**Comment by yurgon** [comment]
is it possible to make parallel importing in Handler ?

**Comment by yurgon** [comment]
Yeah, but its still so long import
how ca I use code like:
File.steam!("big.xml")
|> Stream.chunk_every(30, 30, [])
    |> Task.async_stream(fn x ->
      Enum.each(x, fn m ->
        Repo.transaction(fn ->
          Repo.insert(.......)
        end, pool: DBConnection.Poolboy, pool_timeout: :infinity, timeout: :infinity)
    end)
    end, max_concurrency: (System.schedulers_online), timeout: :infinity)
    |> Stream.run
