### ISSUE TITLE
Allow partial parsing of an XML doc

### ISSUE THREAD

**Issue by liberza** [qcam/saxy#41]
Firstly, this is a very nice library, thanks for making it!

It would be really useful to be able to partially parse a string, return the state, and then when the user gets more input they can pass more of the string in with the previous state, until eventually getting to the end of the xml doc. I tried to see if this was already do-able but it doesn't appear to be. It seems kind of close to streaming... but not quite.

The use case I'm looking at is in a `handle_info/2` function in a GenServer that gets a little bit more of an XML doc each time from a long running process, so I want to update the parsing state each time `handle_info/2` is called.

**Comment by qcam** [comment]
@liberza Glad to hear that you like the library! Currently Saxy doesn't support the feature you described, but indeed it will be very nice to have. Do you think it's similar to what's proposed in #21?

**Comment by liberza** [comment]
At first I thought it wasn't, but at second glance that's pretty much what I'm looking for. I'll close this in favor of that one.
