### ISSUE TITLE
Make partial parser work with fast return

### ISSUE THREAD

**Issue by qcam** [qcam/saxy#45]

**Comment by liberza** [comment]
Hi @qcam, do you have any more details on this issue?

**Comment by qcam** [comment]
@liberza An issue was found with partial parsing a while ago. Saxy supports fast return (https://hexdocs.pm/saxy/Saxy.Handler.html#c:handle_event/3). The user can stop the parsing process at any event emission by returning `{:stop, state}`. When that happens, currently `Partial.parse` returns `{:ok, state}` while `{:ok, partial}` is expected the specs.

**Comment by qcam** [comment]
Closing in favor of #46.
