### ISSUE TITLE
Boolean attribute issue

### ISSUE THREAD

**Issue by paveltyk** [qcam/saxy#48]
Hi,

How can I fix this issue with boolean attr?

```
Saxy.SimpleForm.parse_string(~s|<span itemscope itemtype="https://schema.org/Review"></span>|)

{:error,
 %Saxy.ParseError{
   binary: "<span itemscope itemtype=\"https://schema.org/Review\"></span>",
   position: 16,
   reason: {:token, :eq}
 }}
```

**Comment by qcam** [comment]
Hi @paveltyk, unfortunately attributes without value aren't XML 1.0 compliant (https://www.w3.org/TR/xml/#NT-Attribute). I'd recommend to give the attribute a value if you have the control of it or switch to use a full-fledged HTML parser.

**Comment by paveltyk** [comment]
I see. I wonder if there a quirk mode? Or maybe you can advise with a direction to go with? I would really want to use Saxy in my project.
