### ISSUE TITLE
"&" in characters throws error

### ISSUE THREAD

**Issue by sanconley** [qcam/saxy#50]
First off. Fantastic library. 

I'm getting a `{:token, :reference}` error with contents containing the ampersand(&) character.

```xml
<?xml version='1.0' ?>
<event>
  <sensor>
    <name>Door 1&2</name>
    <location>Upstairs</location>
  </sensor>
</event>
```

I'm parsing a stream from an application that is emitting events for sensors. I can't change what is being emitted.

**Comment by qcam** [comment]
@sanconley Thanks for reporting. Unfortunately `&` is reserved in XML 1.0 for references https://www.w3.org/TR/xml/#NT-Reference, so the provided document is malformed.

Perhaps a hacky solution would be replace `&` with `&amp;` before parsing?

**Comment by sanconley** [comment]
Ya, thats what I'm doing for now. Is there a need to match on `&` in the `:characters` event? I'm asking just to learn, not to be snarky. :)

**Comment by qcam** [comment]
It's totally fine to ask 😄. But what did you mean by matching on `&` in the `:characters` event? :)

**Comment by sanconley** [comment]
I haven't looked into the inner workings of the library, but in the handler, you match on events - one is the `:characters` event. Is that triggered when you come across a `>` until you run into a `</` which sets `:end_element`. When `:characters` is set, can we only look for `</`? That would allow `&` to be used in the value without erroring out.

Not sure how well that is explained, but thank you for taking the time.

**Comment by qcam** [comment]
I think I got what you meant. However, [the grammar of content](https://www.w3.org/TR/xml/#NT-content) (the "data" inside XML tags) is a little more complex.

```
content ::= CharData? ((element | Reference | CDSect | PI | Comment) CharData?)*
```

For instance, content inside the following tag is XML 1.0 compliant:

```xml
<foo>
  Hello World
  <bar>bar content</bar>
  &amp;
  <!--this is comment--->
  Another Hello World
</foo>
```
