### ISSUE TITLE
[HOWTO] Target a nested element

### ISSUE THREAD

**Issue by nresni** [qcam/saxy#54]
Hi,
Is it possible to target a nested element ?

I have this data structure:

```xml
<?xml version="1.0" encoding="utf-8"?>
<identity>
  <name>
    <nested_name>foo</nested_name>
  </name>
  <no_name>
    <nested_name>bar</nested_name>
  </mo_name>
</identity>
```

I would like to have the value of `nested_name` of the first `name` block but not the `nested_name` of the `no_name` block.

Thks

**Comment by qcam** [comment]
Hi, the SAX parser only emits the element that's being parsed but you could build your handler around the structure of the XML, to achieve what you want.

One possible approach is that you can store a flag `is_name_element?` in your parsing state and use it to reason about the data.

```elixir
defmodule MyHandler do
  ...

  def handle_event(:start_element, {"name", _attributes}, state) do
   {:ok,  %{state | is_name_element?: true}}
  end

  def handle_event(:start_element, {"nested_name", _attributes}, state) do
    if state.is_name_element? do
      # the "nested_name" element you want.
    else
      {:ok, state}
    end
  end

  def handle_event(:end_element, "name", state) do
    %{state | is_name_element?: false}
  end
```

**Comment by nresni** [comment]
Thank you for your response
