### ISSUE TITLE
Streaming received chunks of characters event

### ISSUE THREAD

**Issue by erikmocny** [qcam/saxy#55]
Hi,

for start i really like your parser, read also blog post about making it and benchmarking, amazing work mate!

I struggle with one thing at the moment I’m using partial parsing cause i’m receiving big XML over socket so I’m chunking it and it works but…

My use case is this: 

The XML a client is sending to my app contains big attachments as Base64 encoded data (images, PDFs.. etc.) which I need (while parsing / processing) send as stream of chunks to S3-like storage e.g.: 

```
<Object Encoding=“Base64”>
_big_base64encoded_data_binary_
</Object>
```

Here is the catch:
As long as Saxy won’t receive last part of that encoded base64 binary it’s not parsed / valid and Saxy defaults to buffering this element contents until end of that element and therefore loading whole encoded data in memory (this is not acceptable for my use-case and I'm pretty sure I'll not be alone).

What I want to achieve is somehow start stream upload of received chunks of this base64 / element data  as soon as Saxy receives it, but don’t know how to do it without changing internal logic of this library while handling CharData (this concept of having control over what's happening with actual data while parsing them is for example implemented in Stax (Java, https://en.wikipedia.org/wiki/StAX).

Is something like that possible without changing internal logic of Saxy parser as it’s handling characters data? Having this kind of control over received chunks of data will be real benefit and ultimate use-case for me using this library as a stream XML parser with control over emitted events.

Thanks in advance

Erik

**Comment by qcam** [comment]
Hi, thanks for using and liking the library.

I think it should be possible to make the parser emitting `characters` event when the buffer length is greater than a user specified amount, instead of when an opening/closing tag is encountered.

Unfortunately I'm currently quite caught up with personal affair so can't promise to implement this any time soon.
