### ISSUE TITLE
Dialyzer

### ISSUE THREAD

**Issue by varnerac** [qcam/saxy#62]
Will you accept a PR that allows Dialyzer and adds type specs?

**Comment by qcam** [comment]
PRs of missing typespecs would be really welcomed :). I think I would avoid using Dialyzer for now though I'll be very gladly fixing any warning emit by it.

**Comment by varnerac** [comment]
Ok, we will fork it and add dialyzer to our fork. Once we get some specs tightened up, we'll look to contribute them back upstream.
