### ISSUE TITLE
Halt and Partial

### ISSUE THREAD

**Issue by manuel-rubio** [qcam/saxy#67]
Hi @qcam, I think I'm not getting the change done in #66 , I was trying to implement it in my project: https://github.com/altenwald/exampple ; but without success.

What I'm searching for is to get the module Exampple.Xml.Parser.Sender processing the XML chunk and sending the elements one by one to the other process. (I'm sending the PID in the start document event).

Could you address me in the right direction? What should I change to start using your modification?

**Comment by qcam** [comment]
I think this pseudo code of the handler should work.

```elixir
defmodule MyHandler do
  @behaviour Saxy.Handler

  # Omitted other events for brevity.

  def handle_event(:start_element, {tag, _}, stack) do
    [tag | stack]
  end

  def handle_event(:end_element, tag, stack) do
    [^tag | stack] = stack

    if stack == [] do
      # If there is no more element in the stack, which means the document finishes.
      {:halt, :desired_result}
    else  
      {:ok, stack]
    end
  end
end
```

While parsing with partial, I think we need to expect it to return `{:halt, result, rest}` instead of `{:ok, result}`.

```elixir
xml_documents = """
<foo1><foo2></foo2></foo1>
<bar1><bar2></bar2></bar1>
"""

{:ok, partial} = Partial.new(MyHandler, _stack = [])
# Then we parse with the partial until:
{:halt, result, rest} = Partial.parse(partial)
```

Does it make sense to you?

**Comment by manuel-rubio** [comment]
I guess I have to rewrite my stream module from scratch using this approach because it's not working as I expected. Thanks for this, I'll let you know if I achieve advance with this.

**Comment by qcam** [comment]
Thanks, please feel free to reopen this issue if you need more help :).
