### ISSUE TITLE
CDATA: Keep when parsing & rebuilding document

### ISSUE THREAD

**Issue by eteubert** [qcam/saxy#71]
Hi!

I see you're handling CDATA when parsing and it's possible to generate CDATA using a `{:cdata, content}` tuple. What I want to do is parse some XML, edit it and then build XML again. Here's a minimal example using CDATA:

```elixir
 ▶ simplexml
"<?xml version=\"1.0\"?><rss><content:encoded><![CDATA[<strong>foobar</strong>]]></content:encoded></rss>"
▶ {:ok, parsed} = Saxy.SimpleForm.parse_string(simplexml)
{:ok, {"rss", [], [{"content:encoded", [], ["<strong>foobar</strong>"]}]}}
▶ Saxy.encode!(parsed, [])
"<?xml version=\"1.0\"?><rss><content:encoded><strong>foobar</strong></content:encoded></rss>"
```

The final XML is wrong because it does not wrap the `content:encoded` content in CDATA. I looked at the code and I don't think I can solve this by implementing my own event handler as there is no event or indicator for CDATA being returned.

I believe it's a builder bug as well. The generated string without CDATA should look like this:

```xml
<?xml version="1.0"?><rss><content:encoded>&lt;strong&gt;foobar&lt;/strong&gt;</content:encoded></rss>
```

**Comment by qcam** [comment]
Thanks for reporting. I'm very much agree that data returned by simple form parser should generate semantically identical XML document. Perhaps we should start emitting CDATA events as `{:cdata, event}`.

**Comment by qcam** [comment]
Fixed via https://github.com/qcam/saxy/pull/79
