### ISSUE TITLE
Default `Saxy.Builder` implementations have been removed in 1.2.1

### ISSUE THREAD

**Issue by drewolson** [qcam/saxy#74]
This commit https://github.com/qcam/saxy/commit/527bdcafe3afc6ae0c0a08fa73658fa2d86bdd89 removes all of the `Saxy.Builder` implementations. It causes my application to break when upgrading.

I'm assuming their removal was a mistake.

**Comment by qcam** [comment]
Fixed via https://github.com/qcam/saxy/commit/eea7f68c2cefd487c0f026fbf0dca74b89c7a416.

Thanks for reporting. I will publish a new version with the fix.

**Comment by qcam** [comment]
`1.2.2` is on Hex now and `1.2.1` is retired.

**Comment by drewolson** [comment]
Thanks!
