### ISSUE TITLE
Multiple chacarters events being received for the same element when the cdata_as_characters option is enabled

### ISSUE THREAD

**Issue by jhonathas** [qcam/saxy#97]
Hi,

When I receive "character" events with CDATA content, more than one event is emitted for the same element.

Using this example:

         <Neighborhood>
           <![CDATA[CIBRATEL I]]>
         </Neighborhood>

I did an inspection of the content and found it passed my hendle_event 3 times. 
That was my test inspect.
          
          "\n"
          "CIBRATEL I"
          "\n"

Since cdata_as_characters is true, shouldn't only one event come?

I believe that only one event should arrive with the content "\nCIBRATEL I\n".

**Comment by qcam** [comment]
Hi, there is no guarantee that there will be only 1 `:characters` event per element. It's the expected behavior to emit these `:characters` events. One could concatenate them to get the full strings of all the characters though.

**Comment by jhonathas** [comment]
That's what I'm doing right now. I put it to concatenate the received data.

I created a role responsible for this process automatically. Since this behavior is to be expected, I'll keep the function then!

Thanks!
